import apiIndexJson from "../../resources/dartnative-api.json";

export const ICON_CLASSES = [
  "MaterialSymbolsRounded",
  "MaterialSymbolsSharp",
  "MaterialSymbolsOutlined",
  "CupertinoIcons",
] as const;

export type IconClassName = (typeof ICON_CLASSES)[number];

export interface WidgetEntry {
  name: string;
  status: "stable" | "partial";
  note: string;
  section: string;
}

export interface IconEntry {
  name: string;
  verified: boolean;
  sourceFiles: string[];
  derivedFrom?: IconClassName;
}

export interface DartNativeApiIndex {
  generatedAt: string;
  source: {
    repo: string;
    commit: string;
    branch: string;
    docs: string[];
    scannedDartFileCount: number;
  };
  widgets: WidgetEntry[];
  icons: Record<IconClassName, IconEntry[]>;
}

export function isIconClassName(value: string): value is IconClassName {
  return (ICON_CLASSES as readonly string[]).includes(value);
}

/** resources/dartnative-api.json, generated by scripts/generate-api-index.ts — see docs/RESEARCH.md. */
export const apiIndex = apiIndexJson as DartNativeApiIndex;
